/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as GovernmentRouteImport } from './routes/government'
import { Route as IWantToRouteImport } from './routes/i-want-to'
import { Route as ResidentsRouteImport } from './routes/residents'
import { Route as VisitorsRouteImport } from './routes/visitors'
import { Route as DepartmentsSlugRouteImport } from './routes/departments.$slug'
import { Route as VisitorsIndexRouteImport } from './routes/visitors.index'
import { Route as VisitorsChristmasRouteImport } from './routes/visitors.christmas'
import { Route as VisitorsHalloweenRouteImport } from './routes/visitors.halloween'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentRoute = GovernmentRouteImport.update({
  id: '/government',
  path: '/government',
  getParentRoute: () => rootRouteImport,
} as any)
const IWantToRoute = IWantToRouteImport.update({
  id: '/i-want-to',
  path: '/i-want-to',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentsRoute = ResidentsRouteImport.update({
  id: '/residents',
  path: '/residents',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitorsRoute = VisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsSlugRoute = DepartmentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DepartmentsRoute,
} as any)
const VisitorsIndexRoute = VisitorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VisitorsRoute,
} as any)
const VisitorsChristmasRoute = VisitorsChristmasRouteImport.update({
  id: '/christmas',
  path: '/christmas',
  getParentRoute: () => VisitorsRoute,
} as any)
const VisitorsHalloweenRoute = VisitorsHalloweenRouteImport.update({
  id: '/halloween',
  path: '/halloween',
  getParentRoute: () => VisitorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/business': typeof BusinessRoute
  '/departments': typeof DepartmentsRouteWithChildren
  '/government': typeof GovernmentRoute
  '/i-want-to': typeof IWantToRoute
  '/residents': typeof ResidentsRoute
  '/visitors': typeof VisitorsRouteWithChildren
  '/departments/$slug': typeof DepartmentsSlugRoute
  '/visitors/christmas': typeof VisitorsChristmasRoute
  '/visitors/halloween': typeof VisitorsHalloweenRoute
  '/visitors/': typeof VisitorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/business': typeof BusinessRoute
  '/departments': typeof DepartmentsRouteWithChildren
  '/government': typeof GovernmentRoute
  '/i-want-to': typeof IWantToRoute
  '/residents': typeof ResidentsRoute
  '/departments/$slug': typeof DepartmentsSlugRoute
  '/visitors/christmas': typeof VisitorsChristmasRoute
  '/visitors/halloween': typeof VisitorsHalloweenRoute
  '/visitors': typeof VisitorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/business': typeof BusinessRoute
  '/departments': typeof DepartmentsRouteWithChildren
  '/government': typeof GovernmentRoute
  '/i-want-to': typeof IWantToRoute
  '/residents': typeof ResidentsRoute
  '/visitors': typeof VisitorsRouteWithChildren
  '/departments/$slug': typeof DepartmentsSlugRoute
  '/visitors/christmas': typeof VisitorsChristmasRoute
  '/visitors/halloween': typeof VisitorsHalloweenRoute
  '/visitors/': typeof VisitorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/business'
    | '/departments'
    | '/government'
    | '/i-want-to'
    | '/residents'
    | '/visitors'
    | '/departments/$slug'
    | '/visitors/christmas'
    | '/visitors/halloween'
    | '/visitors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/business'
    | '/departments'
    | '/government'
    | '/i-want-to'
    | '/residents'
    | '/departments/$slug'
    | '/visitors/christmas'
    | '/visitors/halloween'
    | '/visitors'
  id:
    | '__root__'
    | '/'
    | '/business'
    | '/departments'
    | '/government'
    | '/i-want-to'
    | '/residents'
    | '/visitors'
    | '/departments/$slug'
    | '/visitors/christmas'
    | '/visitors/halloween'
    | '/visitors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessRoute: typeof BusinessRoute
  DepartmentsRoute: typeof DepartmentsRouteWithChildren
  GovernmentRoute: typeof GovernmentRoute
  IWantToRoute: typeof IWantToRoute
  ResidentsRoute: typeof ResidentsRoute
  VisitorsRoute: typeof VisitorsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government': {
      id: '/government'
      path: '/government'
      fullPath: '/government'
      preLoaderRoute: typeof GovernmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i-want-to': {
      id: '/i-want-to'
      path: '/i-want-to'
      fullPath: '/i-want-to'
      preLoaderRoute: typeof IWantToRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residents': {
      id: '/residents'
      path: '/residents'
      fullPath: '/residents'
      preLoaderRoute: typeof ResidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visitors': {
      id: '/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof VisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/$slug': {
      id: '/departments/$slug'
      path: '/$slug'
      fullPath: '/departments/$slug'
      preLoaderRoute: typeof DepartmentsSlugRouteImport
      parentRoute: typeof DepartmentsRoute
    }
    '/visitors/': {
      id: '/visitors/'
      path: '/'
      fullPath: '/visitors/'
      preLoaderRoute: typeof VisitorsIndexRouteImport
      parentRoute: typeof VisitorsRoute
    }
    '/visitors/christmas': {
      id: '/visitors/christmas'
      path: '/christmas'
      fullPath: '/visitors/christmas'
      preLoaderRoute: typeof VisitorsChristmasRouteImport
      parentRoute: typeof VisitorsRoute
    }
    '/visitors/halloween': {
      id: '/visitors/halloween'
      path: '/halloween'
      fullPath: '/visitors/halloween'
      preLoaderRoute: typeof VisitorsHalloweenRouteImport
      parentRoute: typeof VisitorsRoute
    }
  }
}

interface DepartmentsRouteChildren {
  DepartmentsSlugRoute: typeof DepartmentsSlugRoute
}

const DepartmentsRouteChildren: DepartmentsRouteChildren = {
  DepartmentsSlugRoute: DepartmentsSlugRoute,
}

const DepartmentsRouteWithChildren = DepartmentsRoute._addFileChildren(
  DepartmentsRouteChildren,
)

interface VisitorsRouteChildren {
  VisitorsChristmasRoute: typeof VisitorsChristmasRoute
  VisitorsHalloweenRoute: typeof VisitorsHalloweenRoute
  VisitorsIndexRoute: typeof VisitorsIndexRoute
}

const VisitorsRouteChildren: VisitorsRouteChildren = {
  VisitorsChristmasRoute: VisitorsChristmasRoute,
  VisitorsHalloweenRoute: VisitorsHalloweenRoute,
  VisitorsIndexRoute: VisitorsIndexRoute,
}

const VisitorsRouteWithChildren = VisitorsRoute._addFileChildren(
  VisitorsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessRoute: BusinessRoute,
  DepartmentsRoute: DepartmentsRouteWithChildren,
  GovernmentRoute: GovernmentRoute,
  IWantToRoute: IWantToRoute,
  ResidentsRoute: ResidentsRoute,
  VisitorsRoute: VisitorsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
